IF OBJECT_ID('Sale9468') IS NOT NULL
DROP TABLE Sale9468;

IF OBJECT_ID('Product9468') IS NOT NULL
DROP TABLE PRODUCT9468;

IF OBJECT_ID('Customer9468') IS NOT NULL
DROP TABLE CUSTOMER9468;

IF OBJECT_ID('Location9468') IS NOT NULL
DROP TABLE LOCATION9468;

GO

CREATE TABLE CUSTOMER9468 (
CUSTID	INT
, CUSTNAME	NVARCHAR(100)
, Sales_YTD	MONEY
, STATUS	NVARCHAR(7)
, PRIMARY KEY	(CUSTID) 
);


CREATE TABLE PRODUCT9468 (
PRODID	INT
, PRODNAME	NVARCHAR(100)
, SELLING_PRICE	MONEY
, Sales_YTD	MONEY
, PRIMARY KEY	(PRODID)
);

CREATE TABLE Sale9468 (
SaleID	BIGINT
, CUSTID	INT
, PRODID	INT
, QTY	INT
, PRICE	MONEY
, SaleDATE	DATE
, PRIMARY KEY 	(SaleID)
, FOREIGN KEY 	(CUSTID) REFERENCES CUSTOMER9468
, FOREIGN KEY 	(PRODID) REFERENCES PRODUCT9468
);

CREATE TABLE LOCATION9468 (
  LOCID	NVARCHAR(5)
, MINQTY	INTEGER
, MAXQTY	INTEGER
, PRIMARY KEY 	(LOCID)
, CONSTRAINT CHECK_LOCID_LENGTH CHECK (LEN(LOCID) = 5)
, CONSTRAINT CHECK_MINQTY_RANGE CHECK (MINQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_RANGE CHECK (MAXQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_GREATER_MIXQTY CHECK (MAXQTY >= MINQTY)
);

IF OBJECT_ID('Sale_SEQ') IS NOT NULL
DROP SEQUENCE Sale_SEQ;
CREATE SEQUENCE Sale_SEQ;

GO



